[package]
name = "noise-detector"
version = "0.1.0"
authors = ["bruno.vieira@ilegra.com <bruno319>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
portaudio = "*"